export const places = [
  { name: 'সাজেক', id: 0, score: '3' },
  { name: 'ময়ুঙকপাল', id: 1, score: '2' },
  { name: 'রিসাং ঝর্ণা', id: 2, score: '1' },
  { name: 'তারেং', id: 3, score: '1' },
  { name: 'আলুটীলা', id: 4, score: '1' },
  { name: 'বিছানাকান্দি', id: 5, score: '2' },
  { name: 'রাতারগুল', id: 6, score: '2' },
  { name: 'জাফলং', id: 7, score: '2' },
  { name: 'লালখাল', id: 8, score: '2' },
  { name: 'উৎমাছড়া', id: 9, score: '2' },
  { name: 'সাদাপাথর', id: 10, score: '2' },
  { name: 'তুরংছড়া', id: 11, score: '2' },
  { name: 'মাধবকুন্ডু', id: 12, score: '2' },
  { name: 'মাধবপুর লেক', id: 13, score: '2' },
  { name: 'লাওয়াছড়া', id: 14, score: '1' },
  { name: 'হামহাম ঝর্ণা', id: 15, score: '3' },
  { name: 'চন্দ্রনাথ পাহাড়', id: 16, score: '3' },
  { name: 'নাপিত্তিছড়া ট্রেইল', id: 17, score: '2' },
  { name: 'খৈয়াছড়া', id: 18, score: '2' },
  { name: 'কমলদহ ট্রেইল', id: 21, score: '2' },
  { name: 'সোনাইছড়ি ট্রেইল', id: 22, score: '3' },
  { name: 'সুপ্তধারা,সহস্রধারা', id: 23, score: '2' },
  { name: 'বাশবাড়িয়া', id: 24, score: '1' },
  { name: 'কুমিরাসিবিচ', id: 25, score: '1' },
  { name: 'সন্দিপ', id: 26, score: '2' },
  { name: 'কুয়াকাটা', id: 27, score: '3' },
  { name: 'নিঝুমদ্বীপ', id: 28, score: '3' },
  { name: 'চর কুকরিমুকরি', id: 29, score: '3' },
  { name: 'মনপুরা', id: 30, score: '2' },
  { name: 'ভাসমান পেয়ারাবাজার', id: 31, score: '2' },
  { name: 'বিরিসিরি', id: 32, score: '2' },
  { name: 'বারিক্কাটিলা', id: 33, score: '1' },
  { name: 'টাংগুয়ার হাওর', id: 34, score: '3' },
  { name: 'শিমুলবাগান', id: 35, score: '2' },
  { name: 'টেকেরঘাট', id: 36, score: '1' },
  { name: 'নিলাদ্রি লেক', id: 37, score: '1' },
  { name: 'কাপ্তাই লেক', id: 38, score: '2' },
  { name: 'দুপ্পানি ঝর্ণা', id: 39, score: '2' },
  { name: 'গাছকাটা ঝর্ণা', id: 40, score: '1' },
  { name: 'ণকাটা ঝর্ণা', id: 41, score: '1' },
  { name: 'দুমলং', id: 42, score: '7' },
  { name: 'পতেঙ্গা সি বিচ', id: 43, score: '2' },
  { name: 'নারিকেল সি বিচ', id: 44, score: '2' },
  { name: 'মহেশখালি', id: 45, score: '2' },
  { name: 'সেইন্টমার্টিন', id: 46, score: '4' },
  { name: 'সোনারগাও', id: 47, score: '1' },
  { name: 'মৈনটঘাট', id: 48, score: '1' },
  { name: 'মাওয়াঘাট', id: 49, score: '1' },
  { name: 'আড়িয়াল বিল', id: 50, score: '1' },
  { name: 'নীলগিরি', id: 51, score: '1' },
  { name: 'নীলাচল', id: 52, score: '1' },
  { name: 'স্বর্ম্মন্দির', id: 53, score: '1' },
  { name: 'মেঘলা', id: 54, score: '1' },
  { name: 'অমিয়াখুম জলপ্রপাত', id: 55, score: '7' },
  { name: 'আলীকদম গুহা', id: 56, score: '3' },
  { name: 'কেওক্রাডং', id: 57, score: '5' },
  { name: 'জাদিপাই ঝর্ণা', id: 58, score: '3' },
  { name: 'চিম্বুক পাহাড়', id: 59, score: '2' },
  { name: 'দামতুয়া ঝর্ণা', id: 60, score: '3' },
  { name: 'তিনাপসাইতার', id: 61, score: '4' },
  { name: 'নাফাখুম', id: 62, score: '3' },
  { name: 'নাইক্ষংমুখ', id: 63, score: '1' },
  { name: 'সাতভাইখুম', id: 64, score: '1' },
  { name: 'ভেলাখুম', id: 65, score: '1' },
  { name: 'দেবতাখুম', id: 66, score: '3' },
  { name: 'মহামায়ালেক ক্যাম্প', id: 67, score: '2' },
  { name: 'গুলিয়াখালি', id: 68, score: '1' },
  { name: 'ক্রিসতং', id: 69, score: '5' },
  { name: 'সাকাহাফং', id: 70, score: '1' },
  { name: 'জোতলং', id: 71, score: '8' },
  { name: 'যোগীহাফং', id: 72, score: '6' },
  { name: 'তাজিংডং', id: 73, score: '4' },
  { name: 'ডিমপাহাড়', id: 74, score: '2' },
  { name: 'তলাবং ঝর্ণা', id: 75, score: '2' },
  { name: 'রেমাক্রি', id: 76, score: '3' },
  { name: 'সুন্দরবন', id: 77, score: '4' },
  { name: 'কক্সবাজার', id: 78, score: '1' },
  { name: 'সোয়াচ অফ নো গ্রাউন্ড', id: 79, score: '2' },
  { name: 'হরিংঘাট', id: 80, score: '2' },
  { name: 'বগাকাইন হ্রদ', id: 81, score: '2' },
  { name: 'লিলুক ঝর্ণা', id: 82, score: '3' },
  { name: 'রিজার্ভ ফলস', id: 83, score: '3' },
  { name: 'নিকলী হাওর', id: 84, score: '1' },
  { name: 'ঢিবির হাওর', id: 85, score: '2' },
  { name: 'কালাপাহাড়', id: 86, score: '2' },
  { name: 'মাতায়ন্তং', id: 87, score: '2' },
  { name: 'দেবতাপুকুর', id: 88, score: '2' },
  { name: 'হাজাছরা ঝরনা', id: 89, score: '2' }
];
